### ISSUE TITLE
Restrictive Grails version

### ISSUE THREAD

**Issue by pledbrook** [Arkilog/grails-shiro-ui#1]
Hi,

Please update your `grailsVersion` property in the plugin descriptor. It currently requires a minimum version of 1.3.7! Yes, this is a problem with the template plugin descriptor. We fixed it for Grails 2.0.

BTW, thanks for the plugin.

Peter

**Comment by yellowsnow** [comment]
Hi,

Thanks for your comment, i have set `grailsVersion` to `1.3 > *`, resolution is done in plugin version `1.0-beta3`

Cheers.
